### ISSUE TITLE
postinstall: `typings install`

### ISSUE THREAD

**Issue by draschke** [OfficeDev/Word-Add-in-Angular2-StyleChecker#2]
Hi, 
I get this error with the installation:
npm ERR! node v6.10.0
npm ERR! npm  v2.13.0
npm ERR! code ELIFECYCLE
npm ERR! Word-Add-in-Angular2-StyleChecker@1.0.1 postinstall: `typings install`
npm ERR! Exit status 1

(I'm new with Angular.)
BR, Dirk

was checking for this 
http://stackoverflow.com/questions/35662790/npm-post-install-typings-not-working-correctly/36887161#comment59504242_35904914
and this..
https://github.com/typings/typings/issues/623
but didn't help me.

**Comment by Rick-Kirkham** [comment]
Thanks for bringing this up. I'll try to reproduce and report back here soon.

**Comment by Rick-Kirkham** [comment]
I'm not able to reproduce this. I got different error and fixed it by removing an unneeded line from package.json. You could delete your clone and start from scratch, but I don't think the change I made to package.json is going to fix your symptoms. Are there any earlier "ERR"s in the npm-debug.log file (which should be in the root of your project folder)?

**Comment by draschke** [comment]
This is the whole error msg. If you can see anything, which would help, that would be great!
I would think it could have something to do with my path, but I tried it on three different pc.... and all the same. Thanks!!!
> WordAddIn@1.0.1 postinstall T:\git\WordAddIn
> typings install

typings ERR! message Unable to connect to "https://api.typings.org/entries/dt/core-js/tags/0.0.0%2B20160725163759"
typings ERR! caused by write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:ope
nssl\ssl\s23_clnt.c:794:
typings ERR! caused by
typings ERR!
typings ERR! cwd T:\git\WordAddIn
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "T:\\git\\WordAddIn\\node_modules\\typings\\dist\\bin.js"
"install"
typings ERR! node -v v6.10.0
typings ERR! typings -v 1.5.0
typings ERR! code EUNAVAILABLE
typings ERR!
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\b
in\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v2.13.0
npm ERR! code ELIFECYCLE
npm ERR! WordAddIn@1.0.1 postinstall: `typings install`
npm ERR! Exit status 1

**Comment by Rick-Kirkham** [comment]
Your error is coming from the **typings** executable/script. It is trying to call a REST API at https://api.typings.org/entries/dt/core-js/tags/0.0.0%2B20160725163759". The error seems to be about SSL; that is, HTTPS. You might try running  `bash gen-cert.sh` (step 3), and then set the cert to be a trusted root authority _before_ you run `npm install` (step 2). (But first delete everything and re-clone the repo.) Also, before you do anything, uninstall any global installations of typings. The package.json of the sample will install ver 1.4 of typings as a global dependency. You may have a different version installed globally. If none of that works, try searching typings help for "SSL23_GET_SERVER_HELLO:unknown protocol:ope
 nssl\ssl\s23_clnt.c:794" or subsets of that string.
