### ISSUE TITLE
.vscode directory

### ISSUE THREAD

**Issue by brandonkoch6** [OfficeDev/Word-Add-in-Angular2-StyleChecker#3]
I cloned your repo and was playing around with it to start my own add-in project using Angular.  I noticed you have a .vscode directory.  What exactly is this for?  I noticed that if I remove that directory a bunch of JS files are generated when running the server and put into my app directory.  However, if I keep it, then those are removed from the app directory.  Is this something necessary for any add-in using angular?

**Comment by Rick-Kirkham** [comment]
That directory is just an artifact of the editor that was used to create the sample: Visual Studio Code. You do not have to use VSC and you can delete that folder if you use a different editor.
