### ISSUE TITLE
Using IIS Instead of Node.js

### ISSUE THREAD

**Issue by NotFazed** [OfficeDev/Word-Add-in-Angular2-StyleChecker#4]
Hi,

I'm looking to expand the sample to incorporate some ASP.NET WebAPI services.  How do I convert the sample to run in ISS rather than Node?  Any help appreciated.

**Comment by Rick-Kirkham** [comment]
@NotFazed Can you clarify exactly what you have in mind? If you just want the add-in to make calls to a web API, you can add code to the add-in that makes those calls, including to a web API that is hosted by IIS, whether or not the web API is build on the ASP.NET framework. This is an entirely separate question from where the add-in itself is hosted. The add-in can be hosted on node and call a web API that is hosted on IIS.
