### ISSUE TITLE
Update to use office generator

### ISSUE THREAD

**Issue by CourtJesterBob** [OfficeDev/Word-Add-in-Angular2-StyleChecker#6]
Thanks for the sample.  This is good stuff.  My question is that when I try to follow the current documentation on building my own [Office add-in using angular](https://code.visualstudio.com/docs/other/office), it suggests that we use the office generator and yeoman.  It works great and creates an initial project, but I do not seem to be able to use any of the advanced Angular or typescript (javascript) stuff, like interfaces and types.  Whenever I try to use those, the compiler complains.

Is there any way you can update this project to use Office generator?  Or, should we be modeling our new add-ins after this style of programming?

**Comment by Rick-Kirkham** [comment]
@CourtJesterBob Thanks for your interest in Office Add-ins. Updating old samples to match the latest version of the tools is a low priority. And it would be never-ending. I recommend that you raise your problem on StackOverflow where others in the community who have used Angular and Typescript in Office Add-ins may see it and offer suggestions. Be sure to tag the question `office-js` and provide an example of the code that the compiler complains about.
