### ISSUE TITLE
Build issue 

### ISSUE THREAD

**Issue by chetanganguly** [OfficeDev/Word-Add-in-Angular2-StyleChecker#8]
Hi
I have created word add-in using this sample but i'm facing issue to deploy application on server .
since it doesn't have angular cli i'm not able to create build. Can anyone suggest how to create production build ?
**Its urgent** 

regads
chetan

**Comment by Rick-Kirkham** [comment]
An add-in is basically just a web app. You deploy it to a production server the same way you deploy any other web app to a server. 

Regarding angular cli, you can just install it, can't you?

**Comment by Rick-Kirkham** [comment]
This doesn't seem to be an issue with the sample itself, so I'm going to close this.
